### ISSUE TITLE
Hello :D

### ISSUE THREAD

**Issue by jurmik0** [Batlez/Batlez-Tweaks#1]
Is it safe i dont want to open file that make cant me login to pc

**Comment by sintrode** [comment]
> all of the tweaks are ass, its cool its open source, but the tweaks are TERRIBLE.

Can you elaborate on that? What specific issues are you experiencing?

**Comment by Batlez** [comment]
> Is it safe i dont want to open file that make cant me login to pc

Yes it is safe to use. You can also read which option does what since it is open source.

**Comment by Batlez** [comment]
> all of the tweaks are ass, its cool its open source, but the tweaks are TERRIBLE.

Please open a pull request and fix all of the tweaks that are terrible. Thanks!

**Comment by VerzeHxD** [comment]
i would have to completely re-write the whole batch file
