### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by Galamooth** [Batlez/Batlez-Tweaks#2]
Hola, This tool is effective and very powerful. I love it. But I have a problem that I hope you can help me solve. Microsoft store does not work correctly after applying the script. Could you tell me how to make it work again? I try to check for updates in the store and a triangle appears with an s Exclamation mark and when searching for the apps I use the store closes. Please help me get it back

**Comment by Batlez** [comment]
To fix Microsoft Store, you will have to enter powershell (as admin) and enter the following:

``Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"} ``

If that doesn't work, try running a widget command from the command prompt (as admin):

``winget install 9WZDNCRFJBMP``

**Comment by Galamooth** [comment]
> To fix Microsoft Store, you will have to enter powershell (as admin) and enter the following:
> 
> `Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"} `
> 
> If that doesn't work, try running a widget command from the command prompt (as admin):
> 
> `winget install 9WZDNCRFJBMP`

Thank you. I solved it by starting a service that the script disabled. But I have 2 more problems. Hello. Please help me, after using the script. The key prtsc does not capture the screen like it used to. I pressed fn+ptrsc and the snipping tool opened to take a screenshot.How can I solve that?

The other problem is that the Bluetooth stopped working. I loved the tool. I only have these two problems.

**Comment by Galamooth** [comment]
Solved
